// This file was generated by Prisma, and assumes you have installed the following:
import 'dotenv/config';
import { defineConfig } from '@prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
    shadowDatabaseUrl: process.env['SHADOW_DATABASE_URL'],
  },
  // Shadow database için aynı database'i kullan (development only)
  // Production'da shadow database ayrı olmalı veya kullanıcıya CREATEDB izni verilmeli
});
